export const categories = [
  { name: "Furniture", icon: "Armchair", count: 1240 },
  { name: "Lighting", icon: "Lamp", count: 856 },
  { name: "Flooring", icon: "Square", count: 634 },
  { name: "Kitchen", icon: "ChefHat", count: 912 },
  { name: "Bathroom", icon: "Bath", count: 478 },
  { name: "Decor", icon: "Flower2", count: 1567 },
  { name: "Curtains", icon: "PanelTop", count: 389 },
  { name: "Paint", icon: "Paintbrush", count: 245 },
];

export const featuredVendors = [
  {
    id: "1",
    businessName: "Artisan Woodworks",
    category: "Furniture",
    city: "Mumbai",
    rating: 4.8,
    reviewCount: 124,
    verificationStatus: "premium",
    logo: "",
    description: "Handcrafted solid wood furniture for modern homes",
    productCount: 48,
  },
  {
    id: "2",
    businessName: "LuxeLights Studio",
    category: "Lighting",
    city: "Bangalore",
    rating: 4.6,
    reviewCount: 89,
    verificationStatus: "verified",
    logo: "",
    description: "Designer lighting solutions for every space",
    productCount: 72,
  },
  {
    id: "3",
    businessName: "Stonecraft India",
    category: "Flooring",
    city: "Jaipur",
    rating: 4.9,
    reviewCount: 201,
    verificationStatus: "premium",
    logo: "",
    description: "Premium marble and stone flooring",
    productCount: 36,
  },
  {
    id: "4",
    businessName: "ModKitchen Co.",
    category: "Kitchen",
    city: "Delhi",
    rating: 4.5,
    reviewCount: 67,
    verificationStatus: "verified",
    logo: "",
    description: "Modular kitchen solutions and accessories",
    productCount: 95,
  },
];

export const b2bProducts = [
  {
    id: "b1",
    title: "Luxury Chesterfield Velvet Sofa Set, 3+2+1 Seating Arrangement",
    price: "₹ 85,000",
    vendorName: "Artisan Interiors",
    city: "Mumbai",
    material: "Premium Velvet & Solid Teak",
    finish: "Deep Emerald / Gold Legs",
    rating: 4.8,
    reviews: 124,
    years: 8,
    responseRate: "92%",
    isIndustryLeader: true,
    hasTrustSeal: true,
    gst: true,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800&auto=format&fit=crop",
    video: true
  },
  {
    id: "b2",
    title: "Italian Carrara Marble Slabs, High-Gloss Mirror Finish",
    price: "₹ 450 / sq.ft",
    vendorName: "Stonecraft Jaipur",
    city: "Jaipur, Rajasthan",
    material: "Natural Italian Marble",
    finish: "Book-Matched Polish",
    rating: 4.9,
    reviews: 204,
    years: 15,
    responseRate: "88%",
    isIndustryLeader: true,
    hasTrustSeal: true,
    gst: true,
    image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "b3",
    title: "Modern Handleless Modular Kitchen, UV High Gloss Finish",
    price: "₹ 3,50,000",
    vendorName: "EuroKitchen Systems",
    city: "Bengaluru",
    material: "Marine Grade Plywood",
    finish: "Anti-Scratch Acrylic",
    rating: 4.6,
    reviews: 87,
    years: 6,
    responseRate: "95%",
    isIndustryLeader: false,
    hasTrustSeal: true,
    gst: true,
    image: "https://images.unsplash.com/photo-1556911220-e15224bbaf4b?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "b4",
    title: "Art Deco Brass Chandelier with Hand-Blown Glass",
    price: "₹ 24,000",
    vendorName: "Lumina Lighting Studio",
    city: "Firozabad, UP",
    material: "Solid Brass & Crystal",
    finish: "Antique Gold",
    rating: 4.7,
    reviews: 156,
    years: 12,
    responseRate: "82%",
    isIndustryLeader: true,
    hasTrustSeal: true,
    gst: true,
    image: "https://images.unsplash.com/photo-1524484478789-3473caad80b5?q=80&w=800&auto=format&fit=crop",
  }
];

export const trendingProducts = [
  {
    id: "p1",
    title: "Walnut Dining Table — 6 Seater",
    price: "₹45,000 – ₹65,000",
    vendor: "Artisan Woodworks",
    vendorId: "1",
    city: "Mumbai",
    views: 1243,
    verified: true,
    category: "Furniture",
    image: "",
  },
  {
    id: "p2",
    title: "Brass Pendant Chandelier",
    price: "₹12,500",
    vendor: "LuxeLights Studio",
    vendorId: "2",
    city: "Bangalore",
    views: 876,
    verified: true,
    category: "Lighting",
    image: "",
  },
  {
    id: "p3",
    title: "Italian Carrara Marble Tile",
    price: "₹320 / sq.ft",
    vendor: "Stonecraft India",
    vendorId: "3",
    city: "Jaipur",
    views: 2105,
    verified: true,
    category: "Flooring",
    image: "",
  },
  {
    id: "p4",
    title: "Handleless Modular Kitchen",
    price: "₹2,50,000+",
    vendor: "ModKitchen Co.",
    vendorId: "4",
    city: "Delhi",
    views: 654,
    verified: true,
    category: "Kitchen",
    image: "",
  },
  {
    id: "p5",
    title: "Velvet Tufted Sofa — 3 Seater",
    price: "₹38,000",
    vendor: "Artisan Woodworks",
    vendorId: "1",
    city: "Mumbai",
    views: 987,
    verified: true,
    category: "Furniture",
    image: "",
  },
  {
    id: "p6",
    title: "Minimalist Floor Lamp — Matte Black",
    price: "₹8,900",
    vendor: "LuxeLights Studio",
    vendorId: "2",
    city: "Bangalore",
    views: 543,
    verified: true,
    category: "Lighting",
    image: "",
  },
];

export const dashboardStats = {
  profileViews: { value: 2847, change: 12.5 },
  productViews: { value: 8432, change: -3.2 },
  inquiries: { value: 142, change: 24.1 },
  conversionRate: { value: 4.8, change: 1.2 },
};

export const recentInquiries = [
  {
    id: "inq1",
    customerName: "Rahul Sharma",
    email: "rahul@example.com",
    phone: "+91 98765 43210",
    product: "Walnut Dining Table — 6 Seater",
    message: "Hi, I'm interested in this table. Is it available in a lighter shade? Also, do you deliver to Pune?",
    status: "new",
    date: "2026-03-18",
  },
  {
    id: "inq2",
    customerName: "Priya Mehta",
    email: "priya@example.com",
    phone: "+91 91234 56789",
    product: "Velvet Tufted Sofa",
    message: "Can I get a custom color for the sofa? Looking for a deep emerald green.",
    status: "responded",
    date: "2026-03-17",
  },
  {
    id: "inq3",
    customerName: "Vikram Patel",
    email: "vikram@example.com",
    phone: "+91 87654 32109",
    product: "Custom Bookshelf",
    message: "Need a floor-to-ceiling bookshelf for my study. Can you do custom dimensions?",
    status: "new",
    date: "2026-03-16",
  },
  {
    id: "inq4",
    customerName: "Sneha Gupta",
    email: "sneha@example.com",
    phone: "+91 76543 21098",
    product: "Walnut Dining Table — 6 Seater",
    message: "What's the delivery timeline for Mumbai? And do you offer assembly?",
    status: "closed",
    date: "2026-03-14",
  },
];

export const vendorProducts = [
  {
    id: "vp1",
    title: "Walnut Dining Table — 6 Seater",
    price: "₹45,000 – ₹65,000",
    category: "Dining",
    status: "active",
    views: 1243,
    image: "/solid_teak_dining_table_product_1773926706310.png",
  },
  {
    id: "vp2",
    title: "Velvet Tufted Sofa — 3 Seater",
    price: "₹38,000",
    category: "Living Room",
    status: "active",
    views: 987,
    image: "/modern_lshape_sofa_product_1773926723665.png",
  },
  {
    id: "vp3",
    title: "Oak Study Desk — Compact",
    price: "₹22,000",
    category: "Study",
    status: "inactive",
    views: 456,
    image: "",
  },
  {
    id: "vp4",
    title: "Custom Bookshelf — Floor to Ceiling",
    price: "₹55,000+",
    category: "Storage",
    status: "active",
    views: 678,
    image: "",
  },
  {
    id: "vp5",
    title: "Bedside Table — Pair",
    price: "₹12,500",
    category: "Bedroom",
    status: "active",
    views: 321,
    image: "",
  },
];

export const analyticsData = [
  { name: "01 Mar", views: 400, inquiries: 24, revenue: 2400 },
  { name: "05 Mar", views: 1200, inquiries: 45, revenue: 4500 },
  { name: "10 Mar", views: 900, inquiries: 32, revenue: 3200 },
  { name: "15 Mar", views: 2400, inquiries: 84, revenue: 8400 },
  { name: "20 Mar", views: 1800, inquiries: 56, revenue: 5600 },
  { name: "25 Mar", views: 2800, inquiries: 92, revenue: 9200 },
  { name: "30 Mar", views: 3200, inquiries: 110, revenue: 11000 },
];

export const inquiryDistribution = [
  { name: "Furniture", value: 45, color: "#BF953F" },
  { name: "Lighting", value: 25, color: "#22C55E" },
  { name: "Decor", value: 15, color: "#3B82F6" },
  { name: "Other", value: 15, color: "#94A3B8" },
];

